### ISSUE TITLE
Missing controls icons

### ISSUE THREAD

**Issue by LittleBlin** [ThatGravyBoat/Craftify#112]
Using deadbeef with beefweb and for some reason the controls icons appear to be missing?
![image](https://github.com/ThatGravyBoat/Craftify/assets/97003240/aa02233c-ff0b-4c76-a5e9-cf84a578e8b8)
This is what mc's logs are telling me:
[23:37:36] [Render thread/ERROR]: Signature is missing from Property textures
[23:37:39] [Render thread/ERROR]: Signature is missing from Property textures
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.io.FileNotFoundException: http://localhost:8880/api/artwork/p1/67
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: Caused by: java.io.FileNotFoundException: http://localhost:8880/api/artwork/p1/67
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2018)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at tech.thatgravyboat.craftify.utils.RenderUtils.getImage(RenderUtils.kt:33)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at tech.thatgravyboat.craftify.ui.UIPlayer$updateState$1.invoke$lambda-4$lambda-2(UIPlayer.kt:121)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:39:14] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	... 6 more
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.io.FileNotFoundException: http://localhost:8880/api/artwork/p1/100
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: Caused by: java.io.FileNotFoundException: http://localhost:8880/api/artwork/p1/100
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2018)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at tech.thatgravyboat.craftify.utils.RenderUtils.getImage(RenderUtils.kt:33)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at tech.thatgravyboat.craftify.ui.UIPlayer$updateState$1.invoke$lambda-4$lambda-2(UIPlayer.kt:121)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:39:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	... 6 more
[23:40:03] [Render thread/ERROR]: Signature is missing from Property textures
[23:40:04] [Render thread/INFO]: Generating YACL screen
[23:40:05] [Render thread/INFO]: Generating YACL screen
[23:40:05] [Render thread/WARN]: Warning! Mod craftify has a broken icon, loading default icon
[23:40:13] [Render thread/ERROR]: Signature is missing from Property textures
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-7/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-10/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-11/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-9/INFO]: [STDERR]: 	... 6 more
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: read(connection.inputStream) must not be null
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.get(UIImage.kt:175)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at gg.essential.elementa.components.UIImage$Companion.ofURL$lambda-1(UIImage.kt:137)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:40:13] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	... 6 more

**Comment by LittleBlin** [comment]
(Oh, and for some reason art covers dont load too, but its probably beefweb's fault)

**Comment by LittleBlin** [comment]
Oh, there's already an issue about it, whoops. Sorry.
